name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  mocha-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Create .env file from secrets
        run: |
            echo "MYSQL_ADDON_HOST_TEST=${{ secrets.MYSQL_ADDON_HOST_TEST }}" >> .env
            echo "MYSQL_ADDON_DB_TEST=${{ secrets.MYSQL_ADDON_DB_TEST }}" >> .env
            echo "MYSQL_ADDON_USER_TEST=${{ secrets.MYSQL_ADDON_USER_TEST }}" >> .env
            echo "MYSQL_ADDON_PASSWORD_TEST=${{ secrets.MYSQL_ADDON_PASSWORD_TEST }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Run Mocha tests
        run: npm run test
